### ISSUE TITLE
prepare() on null in DB2.php

### ISSUE THREAD

**Issue by snip3r-dev** [AhmedElywa/Tatar-War#2]
عند استعراض السكربت .. يظهر هذا الخطأ : 
Fatal error: Uncaught Error: Call to a member function prepare() on null in C:\Program Files (x86)\Ampps\www\Tatar-War-master\system\library\DB2.php on line 36 Error: Call to a member function prepare() on null in C:\Program Files (x86)\Ampps\www\Tatar-War-master\system\library\DB2.php on line 36 Call Stack: 0.0000 356648 1. {main}() C:\Program Files (x86)\Ampps\www\Tatar-War-master\index.php:0 0.0010 376936 2. require_once('C:\Program Files (x86)\Ampps\www\Tatar-War-master\Applic\bootstrap.php') C:\Program Files (x86)\Ampps\www\Tatar-War-master\index.php:22 0.0170 577184 3. Servers_Model->GetSettings() C:\Program Files (x86)\Ampps\www\Tatar-War-master\Applic\bootstrap.php:45 0.0170 577456 4. DB2::get_field() C:\Program Files (x86)\Ampps\www\Tatar-War-master\Applic\models\Servers.php:19 0.0170 577456 5. DB2::query() C:\Program Files (x86)\Ampps\www\Tatar-War-master\system\library\DB2.php:62

**Comment by Ahmed2Game** [comment]
be sure you are connect to database in (settings/db.php)

**Comment by snip3r-dev** [comment]
Bad script 
much errors

**Comment by AhmedElywa** [comment]
تم حل المشكله حمل السكربت من جديد
