### ISSUE TITLE
مشكلة في اضافة سيرفر

### ISSUE THREAD

**Issue by HaMaDa2400** [AhmedElywa/Tatar-War#3]
السلام عليكم

في البداية شكرا لك على تنزيل السكريبت لدي مشكلة عند اضافة سيرفر جديد من خلال السيبانل الخطا هذا
Notice: Undefined variable: cpanel_url in /AdminCP/app/controllers/servers.php on line 41
-/AdminCP/system/library/Loader.php : 58
-/AdminCP/app/bootstrap.php : 51
-/AdminCP/index.php : 23
انا شغال على php7.2
وسؤال هل ينفع ازيد السرعة او يصير مشاكل

ومشكور جداً

**Comment by HaMaDa2400** [comment]
وعلما عدلت رابط السيبانل في ملف db

**Comment by AhmedElywa** [comment]
المشكلة اتحلت او لا
