### ISSUE TITLE
مشكلة في البيانات

### ISSUE THREAD

**Issue by HaMaDa2400** [AhmedElywa/Tatar-War#4]
السلام عليكم

عند الانتهاء من اضافة السيرفر وجميع الخطوات جيت اسجل او اسجل دخول يضل بالاصفر يعطي لود ولا يصير شي

**Comment by AhmedElywa** [comment]
وعليكم السلام حط رابط موقعك بشوف المشكله

**Comment by HaMaDa2400** [comment]
المشكلة لم تنحل بعد

تفضل رابط الموقع

http://sutatar.com

**Comment by HaMaDa2400** [comment]
وسؤال استاذ احمد ماذا يفيد تعديل الهاتكس الذي مكتوب

**Comment by HaMaDa2400** [comment]
انتبهت جدول القرى فارغ تماماً عند انشاء سيرفر او اعاادته برجاء المتابعة

**Comment by AhmedElywa** [comment]
تم حل مشكله الاتصال بالقاعده برجاء اعداة تحميل السكربت من جديد

**Comment by HaMaDa2400** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/47034070/58122349-1d0a9880-7c12-11e9-89f6-482869c5c074.png)
![Screenshot_3](https://user-images.githubusercontent.com/47034070/58122353-21cf4c80-7c12-11e9-811e-ccf519f3048b.png)

استاذي الكريم للان يوجد مشاكل فيه علماً نسخة
php 7.1
وجربت
php 7.2

نفس المشكلة واحيانا يطلع اخطاء كثيرة بلوحة التحكم برجاء التاكد

**Comment by AhmedElywa** [comment]
فيك ترسل بيانات الاستضافه تبعك علي البريد الالكتروني 
ahmed2game@gmail.com
or whatsapp 00201275545187
ونا هساعدك

**Comment by HaMaDa2400** [comment]
تم التواصل وشكرا لك
