### ISSUE TITLE
فيه اخطاء بتجيلي

### ISSUE THREAD

**Issue by Rogico** [AhmedElywa/Tatar-War#5]
المشكلة الاولي مفيش صور بتظهر في الاسكربت

2..
بيجيلي الخطأ ده لما باجي اسطب سيرفر جديد

Fatal error: Maximum execution time of 30 seconds exceeded in C:\AppServ\www\tw\AdminCP\app\models\Install.php on line 398

**Comment by AhmedElywa** [comment]
الخطوات الي انا كاتبها مش للوكل هوست 
لازم يتركب علي موقع اونلاين 
الخطا دا عباره عن ان وقت التثبيت اكبر من الحد الاقصي للطلب الواحد المحدد في اعدادات php in php.ini file
